// DOM elements references
export const translateBtn = document.getElementById('translate-btn')
export const language = document.getElementById('language')
export const aboutNav = document.getElementById('about-nav')
export const experienceNav = document.getElementById('experience-nav')
export const projectsNav = document.getElementById('projects-nav')
export const technologiesNav = document.getElementById('technologies-nav')
export const educationNav = document.getElementById('education-nav')
export const role = document.getElementById('role')
export const cvSpanish = document.getElementById('cv-spanish')
export const cvEnglish = document.getElementById('cv-english')
export const aboutTitle = document.getElementById('about-title')
export const aboutContent = document.getElementById('about-content')
export const experienceTitle = document.getElementById('experience-title')
export const binwusRole = document.getElementById('binwus-role')
export const binwusDescription = document.getElementById('binwus-description')
export const redieluzRole = document.getElementById('redieluz-role')
export const redieluzDescription = document.getElementById('redieluz-description')
export const projectsTitle = document.getElementById('projects-title')
export const projectsContent = document.getElementById('projects-content')
export const rottenTitle = document.getElementById('rotten-title')
export const rottenContent = document.getElementById('rotten-content')
export const apiDocumentations = Array.from(document.querySelectorAll('.api-documentation'))
export const sourceCodes = Array.from(document.querySelectorAll('.source-code'))
export const videos = Array.from(document.querySelectorAll('.yt-video'))
export const labTitle = document.getElementById('lab-title')
export const labContent = document.getElementById('lab-content')
export const balancerTitle = document.getElementById('balancer-title')
export const balancerContent = document.getElementById('balancer-content')
export const gameTitle = document.getElementById('game-title')
export const gameContent = document.getElementById('game-content')
export const gameLinks = Array.from(document.querySelectorAll('.game-link'))
export const technologiesTitle = document.getElementById('technologies-title')
export const educationTitle = document.getElementById('education-title')
export const uruCareer = document.getElementById('uru-career')





